{
 "title": "SSL Cerificates",
 "description": "Show certitificate expiration time, as well as failed ssl connects",
 "tags": [ "ssl" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(ssl_tls_connect_success, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(ssl_tls_connect_success{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Failed SSL Connects History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(up{job=~\"$job\", instance=~\"$instance\"} == 0 or ssl_tls_connect_success{job=~\"$job\", instance=~\"$instance\"} == 0)^0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed SSL Connects - $job",
   "type": "table",
   "description": "Possible reasons:\n- site is down\n- server is down\n- certificate has expired\n- certificate is self-signed\n- other connection errors\n- other certificate errors",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "repeat": "job",
   "targets": [
    {
     "expr": "ssl_tls_connect_success{job=~\"$job\"} == 0"
    }
   ]
  },
  {
   "title": "SSL Certificates",
   "type": "table",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "(((ssl_cert_not_after{job=~\"$job\"} - time())/24/60/60) * on (instance,issuer_cn,serial_no) group_left (dnsnames) ssl_cert_subject_alternative_dnsnames) * on (instance,issuer_cn,serial_no) group_left (subject_cn) ssl_cert_subject_common_name"
    }
   ]
  }
 ]
}